language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TOXENV=py26 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py32 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=pypy PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=pypy3 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=cov PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
  - git config --global user.email "travisci@jasonantman.com"
  - git config --global user.name "travisci"
  - pip install tox
  - pip install codecov
  - pip freeze

script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
      secure: podFGj57dhKrUDRYsGFjpypg46esgNSYlWTJhq4+eG2K+zSiP5gsBsj5Xv2yRjEt27EOroXnUhi8qAe7d0ih26akeq5uoomx2OQ1/GG6EzGqVKfRAHhshSnemSiXy6emn6rfGKEG8dyvepyuq+br9BR8z+4mpUXIPM3RN+jYabJvvy4m7HhyWiCh0x0E60TyBYkopIpibXgT6Gg8gbaWziWYCGaY9ypy1sm5BIfkSMX+Yj1pyAH+dBzyZwZkZ1t0yvuot+5RYkY36qDdwUfX5LFevDcR/kvBvto14pVGl09Q1GFZeqAOoHFmPUogUgfSleAyHNcx6N7WWoQ/5pED7FGALEDBxFLPRKa3eIMN+gHhoJnrBETjrwNzlFOajdfyVx51KFCBtCJWex4MXGqdjhywJSEKqhOvHIJKtva8/IlObnmA5YtoDa/hEeLnoMkREAa6byaNwkI44NDscOtqpjW3t46W9ogFKwyJI/d+fEqRbyu1utY3aEewO8N4SzXov+kekPkA6lyR8t8T6yPCwMSqU1KzAzTBfcojAnI+I0ImWlITG9UvNqaPBnZTEVvksMXKQ54JUU82p7St0Aj/3xWM3IZGj4E9/EZoNiQ58NVc+4pXjr+Dv82Xz3SP9crVyqqB8Paud1dZ7QCAINuIWI5QyTIeEf9qyBWyppZoSKs=
    api_key:
      secure: gHdWYM7KzLCsWKzu8BjvgfRfhwT6JcVQXu3IggBeFgxL9JcYY1oCcAKEtXjnvNrbcFROjAVBsZw5K+GuWuwyYKZd2PFW0gbrS7U2k+5pD8O8jd2IlF0R0leHyeJpv9c/cKj4zR6+RhIAcsdujBsFvd6m5QMtGqLT/0tn3kLC1fYYlw+A4meujBpOMsuLLPhLfL/NW4aht9f0VmaR/+2lNRZ1WOz/FboHLXt+DJcBEDWo3A5mgBh2+vTt2dMi4fXeIoZIpCgrDHf7Pl3AdxsBGSe6K6sIAk0CmwDu7hsyNqhVzrZP/7TLGu9PCwhhDOLqUyIycpocWG5q9zzfgMVBF6gT91Gch+qMSy5JND9F+y9eCTm1iHWxLgOHS5/ZtgRxUc5XMzkw9Uv05Mn1chf3DOcXY80dt8P9eu5KhmEjIbelvP4SOym75EwC5Qs5YTC9MePRd89xS1ZYlohWVCptTYCWXO+DwDz+stmiElAuLIl4QI2S0QyHwysG4EQNPS+Oi2/fS3PeBR7SrniX9G1oqKTP7iQoUDC4cL2cGnBn/9v9yPPRt6TNwWIZfuaQW+dWO78W1LdON84F/32rggOWEmAgM7nfRKB5SGvgoaVK+kLEVgTjpA+5zAtktgbCLYA4LR0ClMUjLYrGve8AudYTJvBjBzSNTPr4jhKpJCiqByY=

branches:
  except:
    - /^noci-.*$/
