language: python
sudo: false
cache: pip
matrix:
  include:
    - python: "2.7"
      env: TOXENV=integration
    - python: "3.7"
      env: TOXENV=integration3
install:
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox==2.7.0
- pip install codecov
- pip freeze
- virtualenv --version
script:
- tox -r
branches:
  except:
  - "/^noci-.*$/"
